"""Rename department.

Revision ID: 03e269100f3e
Revises: ff078962a8f0
Create Date: 2024-10-03 17:01:06.216939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03e269100f3e'
down_revision = 'ff078962a8f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("department", "departments")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("departments", "department")
    # ### end Alembic commands ###
