"""Rename address.

Revision ID: bffbb465fa29
Revises: 03e269100f3e
Create Date: 2024-10-03 17:11:21.713611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bffbb465fa29'
down_revision = '03e269100f3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("departments", "address", new_column_name="location")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("departments", "location", new_column_name="address")
    # ### end Alembic commands ###
